### ISSUE TITLE
Add Insufficient Forensic Visibility in GCP Storage

### ISSUE THREAD

**Issue by korniko98** [wiz-sec/open-cvdb#140]
https://www.mitiga.io/blog/mitiga-security-advisory-insufficient-forensic-visibility-in-gcp-storage

**Comment by 0xdabbad00** [comment]
I don't think this should be added as it seems more like something that would be nice to have, but does not seem to be a security mistake.  As per the response of Google, it is not a vulnerability.  I'm not even sure if this is all that valuable of a wishlist item for defenders, as an attacker could just as easily download data locally and then copy it externally in order to circumvent the logging that AWS is said to do better.
