### ISSUE TITLE
When should issues be combined?

### ISSUE THREAD

**Issue by 0xdabbad00** [wiz-sec/open-cvdb#156]
When this project was first started, I had lumped all over-privileged IAM policies into a [single issue](https://github.com/wiz-sec/open-cvdb/blob/main/vulnerabilities/iam-policies-bypass-overprivileged.yaml) for a few reasons:
1. I didn't want to invest the time in creating issues for all of them.
2. The issues were all very similar.
3. It felt like people and issues could end up being over-represented.  For example, I had at one point asked AWS to fix dozens of managed IAM policies, found both through manual audit and from an IAM linter I created.  If I created unique issues for each of those, then I would be the most prolific "bug hunter" of cloud vulns of all time, and AWS would have far more issues represented than any cloud provider, which all seems like it would paint an inaccurate picture of reality.  The amount of work required by me for the different issues was minimal compared to what many cloudvulns require, and similarly the work involved by others who have found similar issues is usually just a matter of looking at a policy and reporting it. As such that issue is a catch-all for all issues reported by any researchers and is not attributed to any one person. 
4.  The issues all seemed at most medium severity, and possibly in some cases not even low risks.  It feels fair to lump together low severity issues, whereas for similar critical issues it may be more reasonable to generate separate issues.

A related situation is when a critical issue has required multiple links in a chain, or multiple issues were identified, we've still created a single issue.  For example [chaosdb](https://github.com/wiz-sec/open-cvdb/blob/main/vulnerabilities/chaosdb.yaml) had a number of issues involved that led to the ultimate result.  As a general rule, it has seemed reasonable that a single blog post should only result in a single issue.

In contrast, there have been some situations where we created multiple cloudvulndb issues for what seems like a single research effort of similar problems identified.  This is demonstrated in:
- https://github.com/wiz-sec/open-cvdb/blob/main/vulnerabilities/aws-service-catalog-cloudtrail-bypass.yaml
- https://github.com/wiz-sec/open-cvdb/blob/main/vulnerabilities/aws-control-tower-lack-of-cloudtrail-logging.yaml

Each of these are undocumented API issues that didn't result in CloudTrail logs, and were disclosed in the same blog post.
Additionally, https://github.com/wiz-sec/open-cvdb/pull/154 and https://github.com/wiz-sec/open-cvdb/pull/153 are yet more undocumented API issues from the same researcher.

This raises the question of whether some or all 4 of those should be combined together?  Would it make a difference if it was a separate researcher that found each one and not part of a single effort?  For example, there have been other undocumented API issues recorded, such as https://github.com/wiz-sec/open-cvdb/blob/main/vulnerabilities/aws-codestar-privilege-escalation.yaml  Should we retroactively lump findings together or add findings to existing similar ones?

If someone ran some spidering tool against the AWS web console and diff'd the APIs found vs the ones in the SDK to identify undocumented APIs and found say 100 undocumented APIs (I have no idea what the actual number may be) would that be a finding for each one?  Would they need to identify security risks with them?

**Comment by Frichetten** [comment]
Hey friends 👋 ,

Throwing my 2 cents in here. To be clear, I don't have strong feelings either way other than to try to guide the project towards a good outcome.

In general, I think it is good to have separate findings for separate issues identified. This provides the largest degree of granularity and accurately describes the risk presented by the vulnerabilities that were discovered. It also makes it easy from a statistical/querying perspective as well. If, say, 5 years from now if someone wanted to find all known vulnerabilities related to AWS ECR, they should be able to query the dataset for `affectedServices: ECR` and get a list of all those vulnerabilities. It would be a problem if they then had to root through each of those findings and try to tally up how many vulnerabilities each of those represented (assuming some were merged). 

The case you provided for merged findings is a good one, and it makes sense that we wouldn't want to burden the system with tens (hundreds?) of findings all of the same category. 

That being said, I don't think that grouping vulnerabilities by category is likely to scale to other issues. For instance, with undocumented APIs it does not make sense to group something like the recent [ECR](https://www.cloudvulndb.org/public-ecr-undocumented-api) vulnerability (which abused undocumented APIs) to something like #154. They both abused undocumented APIs but the impacts are on opposite ends of the spectrum. This also makes it difficult to share or discuss. If I want to talk about Gafnit's amazing work, I should be able to link directly to the page for it, not the general undocumented API page and find it there. 

To provide a less extreme example, if we wanted to discuss XSS in the AWS Console we could look at [XSS on EC2 web console](https://www.cloudvulndb.org/ec2-console-xss) and [Elastic Beanstalk - XSS in Web Console](https://www.cloudvulndb.org/aws-xss-console). These are both XSS vulns in the AWS Console (and have the same impact) but they affect different services, have different exploitability factors, etc. Because CloudVulnDB is acting as a source of truth of cloud vulnerabilities (where the CSPs fail to), it should record all the vulnerabilities found and be an archive for the community.

When it comes to being a part of the same blog post, I don't know if merging them based on that will be effective to prevent flooding the service. If someone was solely interested in drumming up their findings count, they could just create separate blog posts. Or if someone is working on a massive project that will take months to complete (I'm looking at myself here), and they find multiple findings, perhaps across different services, it doesn't make a ton of sense to link them all together because they were all disclosed at the same time.

In regards to the [chaosdb](https://www.cloudvulndb.org/chaosdb) example, I think it makes sense for that to be split up if it is composed of multiple vulnerabilities. I recognize this could cause problems for discussion and sharing that I mentioned earlier, but perhaps that could be countered by creating an overview page for Critical vulnerability chains? Some kind of landing page titled `ChaosDB` that would then link within it to the sub-vulnerabilities that made up that vuln chain? (Just a thought). And that overview page would be excluded so as not to muddy up the stats. Individual vulns do not exist in a vacuum and a subcomponent of ChaosDB could certainly be of interest to the community.

If we compare to the CVE database, they don't merge vulnerabilities there, and it's not uncommon for numerous similar vulnerabilities to be dropped at a time. As an additional component, as our industry matures and we get better and better at finding vulnerabilities in our respective cloud providers, we may move away from blog posts entirely and solely rely on CloudVulnDB to record those vulnerabilities. 

So how do we go about ensuring we don't flood CloudVulnDB with too many of the same issue all at once? Perhaps we could have a compromise for Low vulnerabilities? If multiple are found together, and their severity is Low, we can group them together (while being sure to articulate that a single entry is made up of multiple findings). Again, I don't think this is the right way to go about it, but I do agree that a ton of findings for over-privileged IAM policies would not be a great outcome either. Perhaps the community accounts for this on a case by case basis? Are there any other similar situations where a single entry on CloudVulnDB is made up of multiple vulns/issues?

As an aside, I wanted to comment on 2 of the vulnerabilities mentioned previously: [CloudTrail bypass for AWS Service Catalog](https://www.cloudvulndb.org/aws-service-catalog-cloudtrail-bypass) and [Partial CloudTrail logging in AWS Control Tower](https://www.cloudvulndb.org/aws-control-tower-lack-of-cloudtrail-logging). These two should definitely be kept separate. They are two different issues (one is a CloudTrail bypass by using development endpoints, whereas the other is an example of insufficient logging on the part of CloudTrail. I.E: It just straight up wasn't logging failures), in two different services, with two different impacts. They were released in the same blog post because they were found around the same time. Other than that, they are entirely unrelated to each other. Additionally, those 2 were found during my work at Datadog, whereas #154 and #153 were found in my free time due to a research project I'm pursuing. Further emphasizing that they should not all be lumped together.

**Comment by 0xdabbad00** [comment]
Thank you for the clarification and input! I agree it seems best if we try to align with how CVEs are tracked.  

This repo does include some things and has some goals that don't align directly with CVEs, such as including SOC-2 findings (which I know some folks are not thrilled that I insist on including).  We also work in a way that is slightly different than CVEs in that in many cases it is not the security researcher, and never the cloud provider, that is reporting the issues to us, which results in some additional differences.  So we may not always align with how CVEs do things.

**Comment by 0xdabbad00** [comment]
To bring some conclusion to this, after some private discussion with @korniko98, at a high level, the primary goal of this project is to "collect" cloudvulns, but the "organization" of them is a lesser goal.  What this means is that we want to ensure we include references to all cloudvulns, but we may end up doing so in a way that does not break up blog posts into individual issues.  If someone files a PR that does this for us, then we should accept it, but we may not end up doing so ourselves.  As issues are collected, and patterns and use cases of the data are identified, it may make sense to go back and retroactively fix some things up to align with some sort of defined methodologies, taxonomies, etc.  But the initial goal for us should be to collect this data, and if such changes were to happen, I would want that to happen broadly across all existing issues, and not a single or handful of select issues. 

So to give a concrete example of this, for the recent [blog post](https://frichetten.com/blog/minor-cross-tenant-vulns-app-runner/) and the PRs #154 and #153 that Nick submitted as a result of it, if Nick had not submitted those PRs, it is likely we would have just filed it as a single issue, but given the PRs were made that helps the organization of the data, it makes sense to merge them as is.  I want to avoid us cherry picking specific issues to better organize them though, so if we had already added it as a single issue, and someone desired that it be broken up, I would prefer not to have us doing that, even if it was requested via a PR that does it for us.  My reasoning is that I want to avoid modifying issues once they are added.

I recognize this is not ideal, but perfectly organizing all the data around this would be a very large time commitment otherwise (possibly a full time job for multiple people).  I recognize that many people wish this data was better organized in certain ways as they want a perfect data set which they can use to compare the cloud providers and look for trends over time, but concepts around how to organize this data are still being developed, and it seems best for us to prioritize on ensuring we have the largest corpus of this data, rather than what would result in being a smaller subset of this data being better organized.

If anyone is reading this and wishes to improve this, please reach out for discussion before taking this as an invitation to create a "competing" data set of some sort.
